### ISSUE TITLE
Callback parameter doesn't seem to be as documented

### ISSUE THREAD

**Issue by symposion** [conventional-changelog/conventional-recommended-bump#11]
The docs say that you get a string "major", "minor", "patch"; in reality you get an object that contains a releaseAs property that contains these values.

**Comment by stevemao** [comment]
PR welcome

**Comment by symposion** [comment]
Which is wrong? Docs or code?

**Comment by stevemao** [comment]
Docs

**Comment by stevemao** [comment]
``` js
var conventionalRecommendedBump = require('conventional-recommended-bump');

conventionalRecommendedBump({
  preset: 'angular'
}, function(err, result) {
  console.log(result.releaseAs);
  //=> 'major'
});
```

Looks like its correct. Reopen if you meant something else

**Comment by symposion** [comment]
Yep, that's correct now. Thanks! Sorry - have been up to my eyeballs and didn't get a chance to send a PR.
