### ISSUE TITLE
idea: bump patch on "chore"

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/conventional-recommended-bump#12]
When `semantic-version` submits a pull request that bumps a dependency version, it's usually the case that you want to release a new point-release with the dependency update. Should `chore` along with `fix` result in a patch bump?

**Comment by stevemao** [comment]
I believe if a updating a dep results in a new feature (or breaking change) for the module, the type should be `feat`. EG:

```
feat(deps): update standard to v7

There is a new feature in v7, and thus we have a new feature here.
```

`chore` should mean there is absolute no changes to the end user. Originally angular uses this type for stuff like changing the gulpfile, update a devDep for the tools etc.

I don't think a bump should always be `chore`.

**Comment by stevemao** [comment]
Thoughts @nexdrew?

**Comment by nexdrew** [comment]
I'm confused. Isn't the default recommended bump always patch in the absence of `feat` commits or BREAKING CHANGE?

**Comment by stevemao** [comment]
Yes, @bcoe is asking whether it should be a minor sometimes if the `type` is chore (I think this is for greenkeeper stuff).

**Comment by bcoe** [comment]
@here oh, I think I was confused; didn't realize we're going to recommend a bump even if it's not a verb we support. misunderstanding on my part.

**Comment by stevemao** [comment]
> didn't realize we're going to recommend a bump even if it's not a verb we support.

A related issue #4 (reading it again, not quite the same :smile:)
