### ISSUE TITLE
remove preset

### ISSUE THREAD

**Issue by stevemao** [conventional-changelog/conventional-recommended-bump#16]
use a config file

**Comment by hutson** [comment]
@stevemao someone recently [submitted a merge request](https://gitlab.com/hyper-expanse/semantic-release-gitlab/merge_requests/18) to allow users of `semantic-release-gitlab` to set their preferred preset.

Right now we're hard-coding a list of presets into the CLI tool.

Should we be taking an alternative approach in anticipation of this issue?

**Comment by hutson** [comment]
Here's an example of using `conventional-commits-detector` in such a way that it returns one commit convention that isn't then supported by `conventional-recommended-bump` - https://gitlab.com/hyper-expanse/semantic-release-gitlab/issues/24#note_38127165

**Comment by hutson** [comment]
Can this issue please be closed out?

**Comment by hutson** [comment]
Long-term I'd like to follow up with conventional-changelog/conventional-changelog/issues/241 to see if we can make `--preset` and the `preset` config option take preset packages.

**Comment by hutson** [comment]
Closing in favor of https://github.com/conventional-changelog/conventional-changelog/issues/241
