### ISSUE TITLE
conventional-recommended-bump does not increment versions in a conventional way.

### ISSUE THREAD

**Issue by mchambaud** [conventional-changelog/conventional-recommended-bump#17]
Latest version **0.3.0** should have been **1.0.0**

According to [SEMVER](http://semver.org/)

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make **incompatible API changes**,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

This impacted our ability to ship code for a day while investigating our broken CI which allowed installing minor version of conventional-recommended-bump.

**Comment by henrymyers** [comment]
Looks good. Good to go

**Comment by stevemao** [comment]
https://github.com/mojombo/semver/issues/221

**Comment by mchambaud** [comment]
@stevemao something tells me your code will be version zero forever and after.

**Comment by mchambaud** [comment]
@stevemao After one year, it would be great to go to version one, don't you think?

**Comment by lucmerceron** [comment]
I agree with @mchambaud on this one, I found it strange that this really useful tool did not respect the [semver](http://semver.org/) convention to determine version to update.
It should increase **MAJOR** on a *Breaking Change* and not increase **PATCH** on something secondary like *chore* commit.

**Comment by stevemao** [comment]
@lucmerceron I **DID** follow semver very carefully. See the above link
