### ISSUE TITLE
conventional-recommended-bump --preset does not pickup local conventional-changelog-lint-config-* package

### ISSUE THREAD

**Issue by gajus** [conventional-changelog/conventional-recommended-bump#19]
``` sh
$ npm install conventional-changelog-lint-config-canonical
$ npm install conventional-recommended-bump
$ conventional-recommended-bump --preset canonical
Error: Preset: "canonical" does not exist
```

**Comment by gajus** [comment]
Looking at the [`./presets/angular.js`](https://github.com/conventional-changelog/conventional-recommended-bump/blob/master/presets/angular.js), it looks like preset is something completely else.

Where is the documentation for this?

**Comment by stevemao** [comment]
I'm probably gonna remove preset since no one is using it. But it will still be configurable (based on angular). https://github.com/conventional-changelog/conventional-recommended-bump/issues/16, https://github.com/conventional-changelog/conventional-recommended-bump/pull/18

**Comment by stevemao** [comment]
I don't know what conventional-changelog-lint-config-canonical is. the preset here is only for this module.

**Comment by stevemao** [comment]
https://github.com/conventional-changelog/conventional-recommended-bump#preset is the doc

**Comment by hutson** [comment]
@stevemao can we please close this issue out?

If any issues or concerns have not been addressed, we should follow up our discussion on the `conventional-changelog` monorepo project.

**Comment by hutson** [comment]
@gajus I've filed conventional-changelog/conventional-changelog/issues/241 to look into supporting external preset packages within `conventional-recommended-bump`, which may address your needs.

**Comment by hutson** [comment]
Closing in favor of https://github.com/conventional-changelog/conventional-changelog/issues/241
