### ISSUE TITLE
Do not fail silently

### ISSUE THREAD

**Issue by gajus** [conventional-changelog/conventional-recommended-bump#20]
``` sh
$ conventional-recommended-bump

```

Produces just an empty output.

**Comment by gajus** [comment]
It appears that `whatBump` quietly defaults to `noop`.

https://github.com/conventional-changelog/conventional-recommended-bump/blob/169fbcf9df7913b45fd23a82036b780ddfcc22a3/index.js#L41

**Comment by gajus** [comment]
Turns out that the `--preset` options has no default value.

This is not much of use (outside of Angular preset), until https://github.com/conventional-changelog/conventional-recommended-bump/issues/19 is fixed.

**Comment by hutson** [comment]
I have re-posted this issue on the `conventional-changelog` monorepo - conventional-changelog/conventional-changelog/issues/242

@stevemao can this issue please be closed out?

**Comment by hutson** [comment]
Closing in favor of https://github.com/conventional-changelog/conventional-changelog/issues/242
