### ISSUE TITLE
README doesn't explain how to trigger it

### ISSUE THREAD

**Issue by Haroenv** [conventional-changelog/conventional-recommended-bump#25]
How does a commit need look to trigger resp. a minor, major or patch change? I saw something with `BREAKING CHANGE:`

**Comment by hutson** [comment]
@Haroenv please see item 3 under the summary on this site - http://conventionalcommits.org/

Most commit conventions support the conventional style of using a `BREAKING CHANGE:` label in the optional body or footer of a commit message.

**Comment by Haroenv** [comment]
perfect, missed it somehow before 👌
