### ISSUE TITLE
Close Out Issues

### ISSUE THREAD

**Issue by hutson** [conventional-changelog/conventional-recommended-bump#26]
This repository has been archived (as I just realized), since the package was merged into the `conventional-changelog` monorepo - https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump

Could the issues, and pull requests, please be closed out to reflect the move?

**Comment by stevemao** [comment]
Sure. Let's move the issues to the main repo.

**Comment by hutson** [comment]
@stevemao how can I help with that? Should I just re-post them, or request each person to re-file their issue to the monorepo?

**Comment by stevemao** [comment]
Just re-post them and link back to the original ones. Thanks!

**Comment by hutson** [comment]
@stevemao I've have gone through all issues and either re-posted them to the `conventional-changelog` monorepo, or simply answered them (in the case of #25).

Would you please consider closing out all issues and then disabling the Issues, Projects, and Wiki features of this GitHub project so as not to cause confusion to new users?

**Comment by hutson** [comment]
@stevemao thank you for allowing me to close out these issues, and your confidence in me.

On a final note, as a housekeeping chore, I'm not able to close out the Projects, Wiki, and Issues pages.
