### ISSUE TITLE
need more presets

### ISSUE THREAD

**Issue by stevemao** [conventional-changelog/conventional-recommended-bump#3]

**Comment by leonardoanalista** [comment]
Maybe allow people to plug their own custom preset?

**Comment by stevemao** [comment]
@leonardoanalista added #6

**Comment by hutson** [comment]
@stevemao could we just pass in [conventional-changelog-angular](https://github.com/stevemao/conventional-changelog-angular)?

**Comment by stevemao** [comment]
@hbetts How?

**Comment by hutson** [comment]
@stevemao well, `conventional-changelog-angular` returns back an object with `parserOpts` and `writerOpts`. `conventional-changelog-angular` could be extended to return a `bumpOpts` containing a `recommend` method. Then `conventional-recommended-bump` could take the preset module as an option under `options.config` similar to how `conventional-changelog` allows you to pass in custom presets.

**Comment by hutson** [comment]
I'm just wondering if we could use the existing preset projects out there rather than needing to include the recommendation function for each preset as part of this project.

Doing that will necessitate using the API supported by `conventional-changelog`, which would make it easy for people to pass in custom presets.

**Comment by stevemao** [comment]
The hard part is not parsing the commit messages. Its how to know if it's a breaking change. Angular has the keyword "BREAKING CHANGE" but most presets don't. Nevertheless, PR welcome if you have a good idea @hbetts .

**Comment by hutson** [comment]
I've re-posted my preset packages idea to conventional-changelog/conventional-changelog/issues/241

Can we please close this issue out?

We can probably just wait for people to file individual preset requests against `conventional-changelog` before worrying about adding additional preset to `conventional-recommended-bump`.

**Comment by hutson** [comment]
Closing in favor of https://github.com/conventional-changelog/conventional-changelog/issues/241
