### ISSUE TITLE
returns "patch" in published package

### ISSUE THREAD

**Issue by olalonde** [conventional-changelog/conventional-recommended-bump#4]
I just did an `npm publish` and `./node_modules/.bin/conventional-recommended-bump --preset=angular` returns `patch` although there aren't any new commits since last publish. Is that the expected behaviour? Shouldn't just the command fail since there is not need to bump to a new version?

**Comment by stevemao** [comment]
Why? If you don't wanna bump why do you run this module?

**Comment by olalonde** [comment]
Because I don't always know if I need to bump or not. Well, it's not a big deal.

**Comment by stevemao** [comment]
There are some cases where you don't have any commit but you wanna do a release. EG my previous release is screwed for some reason.

**Comment by olalonde** [comment]
Yes but in that case, `conventional-recommended-bump` can't figure that out for you and you likely need to use `npm version` by yourself. I think `conventional-recommended-bump` should fail with an error if there are no new commits since last release.

**Comment by stevemao** [comment]
I think this is a good point but I'm not completely convinced yet.

**Comment by stevemao** [comment]
I think I'll just simply `warn` for now.

**Comment by nexdrew** [comment]
Actually I quite like the default behavior, it works very well in libs like `standard-version`, allowing it to run successfully every time. There are several reasons why I might need to publish a new release with either no new commits or only `chore` commits, and bumping the patch is the correct behavior.

That being said, I wouldn't argue with making that configurable, but I wouldn't change the default behavior.

**Comment by stevemao** [comment]
Thinking about his again. `npm version` doesn't fail if there's no commit. I think this should follow the same paradigm

> That being said, I wouldn't argue with making that configurable, but I wouldn't change the default behavior.

It warns (if verbose in cli or pass `options.warn`), so i don't think a config is necessary.
